name: Build
on: [ push ]
jobs:
  gradle:
    strategy:
      matrix:
        os: [ ubuntu-latest ]
    runs-on: ${{ matrix.os }}
    #runs-on: self-hosted
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: '17'
      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2

      - name: Make gradlew executable
        run: chmod +x ./gradlew

      - name: Execute Gradle build
        run: ./gradlew shadowJar

      - name: release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: latest
          files: |
            build/libs/*.jar
          token: "${{ secrets.GITHUB_TOKEN }}"